import Head from 'next/head';
import NavigationBar from '../components/Shared/NavigationBar';
import HomeBanner from '../components/Home/HomeBanner';
import OurSolutionsComponent from '../components/Home/OurSolutionsComponent';
import WppComponent from '../components/Shared/WppComponent';
import OurContactComponent from '../components/Shared/OurContactComponent';
import OurProjectComponent from '../components/Home/OurProjectComponent';
import OurPartnersComponent from '../components/Home/OurPartnersComponent';
import OurFeedBackComponent from '../components/Home/OurFeedBackComponent';
import FooterComponent from '../components/Shared/FooterComponent';

export const getStaticProps = async () => {
    const res_feedback = await fetch(`${process.env.NEXT_PUBLIC_STRAPI_URL}/api/feedbacks?populate=foto`);
    const data_json = await res_feedback.json();
    return {
        props: {
            data: data_json,
        },
    };
};

export default function Home({ data }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <NavigationBar></NavigationBar>
                <HomeBanner></HomeBanner>
                <WppComponent />
                <OurSolutionsComponent />
                <OurContactComponent />
                <OurProjectComponent />
                <OurPartnersComponent />
                {/* <OurFeedBackComponent feedback={data}/> */}
                <FooterComponent />
            </main>
        </>
    );
}
