// Hooks

// Components
import HomeBanner from "../../components/Home/HomeBanner";
import OurPartnersComponent from "../../components/Home/OurPartnersComponent";
import OurProjectComponent from "../../components/Home/OurProjectComponent";
import OurSolutionsComponent from "../../components/Home/OurSolutionsComponent";
import FooterComponent from "../../components/Shared/FooterComponent";
import NavigationBar from "../../components/Shared/NavigationBar";
import OurContactComponent from "../../components/Shared/OurContactComponent";
import WppComponent from "../../components/Shared/WppComponent";

export default function Home() {
	const { feedbackData, loading, error } = useEndpoint('/feedbacks?populate=foto');

	return (
		<>
      		<Head>
        		<title>Create Next App</title>
        		<meta name="description" content="Generated by create next app" />
        		<meta name="viewport" content="width=device-width, initial-scale=1" />
        		<link rel="icon" href="/favicon.ico" />
      		</Head>
    		<main>
    			<NavigationBar />
    			<HomeBanner />
    			<WppComponent />
    			<OurSolutionsComponent />
    			<OurContactComponent />
    			<OurProjectComponent />
    			<OurPartnersComponent />
    			<OurFeedBackComponent feedback={feedbackData}/>
    			<FooterComponent />
    		</main>
    	</>
	)
}